
package app_reportegraficas;

import java.awt.Color;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.XYPlot;
import org.jfree.data.category.DefaultCategoryDataset;

public class JFrame_main extends javax.swing.JFrame {

    public JFrame_main() {
        initComponents();
        jTabbedPane_pestanias.setEnabledAt(0, true);
        jTabbedPane_pestanias.setEnabledAt(1, false);
        buttonGroup_graficas.add(jRadioButton_graph1);
        buttonGroup_graficas.add(jRadioButton_graph2);
        buttonGroup_graficas.add(jRadioButton_graph3);
        jRadioButton_graph1.setSelected(true);
    }
    
    ConexionMySQL conect = new ConexionMySQL();
    pdf pdf = new pdf();
    graficas grafica = new graficas();
    JFreeChart tablaGrafico;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup_graficas = new javax.swing.ButtonGroup();
        jTabbedPane_pestanias = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextF_user = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextF_password = new javax.swing.JPasswordField();
        jButton_login = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton_graficar = new javax.swing.JButton();
        jPanel_grafica = new javax.swing.JPanel();
        jButton_exp = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_1 = new javax.swing.JTable();
        jRadioButton_graph1 = new javax.swing.JRadioButton();
        jRadioButton_graph2 = new javax.swing.JRadioButton();
        jRadioButton_graph3 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jButton_logout = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_3 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea_info = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tasu Chart stable version");
        setResizable(false);

        jTabbedPane_pestanias.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("User:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Password:");

        jButton_login.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_login.setText("Log in");
        jButton_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_loginActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 40)); // NOI18N
        jLabel4.setText("TASU CHART");

        jTextPane1.setEditable(false);
        jTextPane1.setBackground(new java.awt.Color(153, 153, 255));
        jTextPane1.setBorder(null);
        jTextPane1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextPane1.setText("Tasu Chart is an application that allows you to visualize the content of tables from a MySQL database in the form of charts and export them in PDF; with Tasu Chart, you can transform data into clear and concise graphics that will help you better understand the information in your database.");
        jScrollPane6.setViewportView(jTextPane1);

        jLabel8.setText("Developed by Luis Barranco");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_login, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextF_user)
                                .addComponent(jTextF_password, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel4))
                .addGap(306, 306, 306))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 862, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextF_user, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextF_password, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jLabel3))
                .addGap(38, 38, 38)
                .addComponent(jButton_login, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(144, 144, 144)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jLabel8)
                .addContainerGap())
        );

        jTabbedPane_pestanias.addTab("Log in", jPanel2);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Graphs");

        jButton_graficar.setText("Generate Graph");
        jButton_graficar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_graficarActionPerformed(evt);
            }
        });

        jPanel_grafica.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout jPanel_graficaLayout = new javax.swing.GroupLayout(jPanel_grafica);
        jPanel_grafica.setLayout(jPanel_graficaLayout);
        jPanel_graficaLayout.setHorizontalGroup(
            jPanel_graficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 494, Short.MAX_VALUE)
        );
        jPanel_graficaLayout.setVerticalGroup(
            jPanel_graficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 269, Short.MAX_VALUE)
        );

        jButton_exp.setText("Export as PDF");
        jButton_exp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_expActionPerformed(evt);
            }
        });

        jTable_1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id_2005", "Entidad", "Población", "Edad media"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_1);

        jRadioButton_graph1.setText("Graph 1");

        jRadioButton_graph2.setText("Graph 2");

        jRadioButton_graph3.setText("Graph 3");

        jLabel5.setText("Graph type:");

        jButton_logout.setText("Log out");
        jButton_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_logoutActionPerformed(evt);
            }
        });

        jTable_2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id_2010", "Entidad", "Poblacion", "Edad media"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable_2);

        jTable_3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id_2020", "Entidad", "Población", "Edad media"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable_3);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Tables");

        jTextArea_info.setColumns(20);
        jTextArea_info.setRows(5);
        jScrollPane4.setViewportView(jTextArea_info);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Body");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel7))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jRadioButton_graph1, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addComponent(jRadioButton_graph2, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jRadioButton_graph3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton_graficar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton_exp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_logout))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel_grafica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_graficar)
                            .addComponent(jButton_exp)
                            .addComponent(jButton_logout)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel_grafica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton_graph1)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton_graph2)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton_graph3))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jTabbedPane_pestanias.addTab("Tables", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane_pestanias)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane_pestanias)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_loginActionPerformed
        // TODO add your handling code here:
       
        conect.conectar(jTextF_user.getText(), jTextF_password.getText());
        if(conect.estadoConeccion){
            JOptionPane.showMessageDialog(null,"login succeed");
            jTabbedPane_pestanias.setEnabledAt(1, true);
            jTabbedPane_pestanias.setSelectedIndex(1);
            jTabbedPane_pestanias.setEnabledAt(0, false);
            //llenamos la tabla con la info de la base de datos
            conect.mostrarTabla(jTable_1,"poblacion2005");
            conect.mostrarTabla(jTable_2,"poblacion2010");
            conect.mostrarTabla(jTable_3,"poblacion2020");
            jTextF_password.setText("");
        }
    }//GEN-LAST:event_jButton_loginActionPerformed

    private void jButton_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_logoutActionPerformed
        // TODO add your handling code here:
        conect.desconectar();
        if(!conect.estadoConeccion){
            JOptionPane.showMessageDialog(null, "Logout succeed");
            jTabbedPane_pestanias.setEnabledAt(1, false);
            jTabbedPane_pestanias.setSelectedIndex(0);
            jTabbedPane_pestanias.setEnabledAt(0, true);
        }
    }//GEN-LAST:event_jButton_logoutActionPerformed

    private void jButton_expActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_expActionPerformed
        // TODO add your handling code here:
        pdf.exportarPDF(tablaGrafico,"Report",jTextArea_info.getText());
    }//GEN-LAST:event_jButton_expActionPerformed

    private void jButton_graficarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_graficarActionPerformed
        // TODO add your handling code here:
        //limpiamos el panel con cada clic
        jPanel_grafica.removeAll();
        
        DefaultCategoryDataset datos2005 = new DefaultCategoryDataset();
        DefaultCategoryDataset datos2010 = new DefaultCategoryDataset();
        DefaultCategoryDataset datos2020 = new DefaultCategoryDataset();

        for(int i =0;i<jTable_1.getRowCount();i++){
            String estado = jTable_1.getValueAt(i, 1).toString()+" 2005";
            int poblacion = Integer.parseInt(jTable_1.getValueAt(i, 2).toString());
    
            // Agregar la población como valores para el estado correspondiente
            datos2005.addValue(poblacion, "Población 2005", estado);
        }
        
        for(int i =0;i<jTable_2.getRowCount();i++){
            String estado = jTable_2.getValueAt(i, 1).toString()+" 2010";
            int poblacion = Integer.parseInt(jTable_2.getValueAt(i, 2).toString());
    
            // Agregar la población como valores para el estado correspondiente
            datos2010.addValue(poblacion, "Población 2010", estado);
        }
        
        for(int i =0;i<jTable_3.getRowCount();i++){
            String estado = jTable_3.getValueAt(i, 1).toString()+" 2020";
            int poblacion = Integer.parseInt(jTable_3.getValueAt(i, 2).toString());
    
            // Agregar la población valores para el estado correspondiente
            datos2020.addValue(poblacion, "Población 2020", estado);
        }

        //cambiamos dependiendo el tipo de grafica seleccionada
        JFreeChart grafico = null;
        
        if(jRadioButton_graph1.isSelected()){
            grafico = ChartFactory.createXYStepChart("Población", "Entidades", "Población", grafica.convertirXYDataset(datos2005));
            XYPlot plot = (XYPlot)grafico.getPlot();
            plot.setDataset(1, grafica.convertirXYDataset(datos2010));
            plot.setDataset(2, grafica.convertirXYDataset(datos2020));
            //plot.setQuadrantPaint(2, Color.BLUE);
        }else if(jRadioButton_graph2.isSelected()){
            grafico = ChartFactory.createAreaChart("Población", "Entidades", "Población", datos2005);
            grafico.getCategoryPlot().setDataset(1, datos2010);
            grafico.getCategoryPlot().setDataset(2, datos2020);
        }else if(jRadioButton_graph3.isSelected()){
            grafico = ChartFactory.createScatterPlot("Población", "Entidades", "Población", grafica.convertirXYDataset(datos2005));
            XYPlot plot = (XYPlot)grafico.getPlot();
            plot.setDataset(1, grafica.convertirXYDataset(datos2010));
            plot.setDataset(2, grafica.convertirXYDataset(datos2020));
        }
        grafica.agregarGrafica(grafico, jPanel_grafica);
        pack();
        repaint();
        tablaGrafico = grafico;

    }//GEN-LAST:event_jButton_graficarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup_graficas;
    private javax.swing.JButton jButton_exp;
    private javax.swing.JButton jButton_graficar;
    private javax.swing.JButton jButton_login;
    private javax.swing.JButton jButton_logout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel_grafica;
    private javax.swing.JRadioButton jRadioButton_graph1;
    private javax.swing.JRadioButton jRadioButton_graph2;
    private javax.swing.JRadioButton jRadioButton_graph3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane_pestanias;
    private javax.swing.JTable jTable_1;
    private javax.swing.JTable jTable_2;
    private javax.swing.JTable jTable_3;
    private javax.swing.JTextArea jTextArea_info;
    private javax.swing.JPasswordField jTextF_password;
    private javax.swing.JTextField jTextF_user;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
